spring:
  application:
    name: ocu-web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  address: 127.0.0.1
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka
zuul:
  retryable: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#
#feign:
#  hystrix:
#    enabled: true
#
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream





